#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DIR/config/loadConfig"

# ------------------------------------------------
# Main
# ------------------------------------------------
function main {
	case "$1" in
		config)
			installConfig

			exit 0
		;;

		persist)
			makePersist

			exit 0
		;;

		*)
			echo "Usage : $0 {config|persist}"
			exit 1
		;;
	esac
}

# ------------------------------------------------
# Create file who will start VPN and add iptable
# rules when network goes up.
# Only if no "non-persistent" parameter was passed 
# to script.
# ------------------------------------------------
function makePersist {
	cat >> /etc/network/if-up.d/secure-vpn << EOF
#!/bin/bash

"$DIR/secure-vpn" start
EOF

	chmod +x /etc/network/if-up.d/secure-vpn
}

# ------------------------------------------------
# Copy config inside $CONFIG_DIR/ and add
# options to the client.ovpn file
# ------------------------------------------------
function installConfig {
	# If config dir already exist, prompt user to remove it
	if [ -d "$CONFIG_DIR" ]; then
		read -p "Config dir already exists. Remove & recreate it ? (y/n)?"
		if [ "$REPLY" == "y" ]; then
			rm -rf "$CONFIG_DIR"
		else
			echo "Exiting..."
			exit 1
		fi
	fi

	mkdir "$CONFIG_DIR"

	cp -r "$DIR/config/"* "$CONFIG_DIR/"

	# Get line where the fun starts
	startLine=$(awk '$0 ~ str{print NR FS b}{b=$0}' str="### CUSTOM PATHS ###" "$CONFIG_DIR/client.ovpn")

	# Keep only first part of the file (remove "custom" options at the end)
	head -n $startLine "$CONFIG_DIR/client.ovpn" > "$CONFIG_DIR/client.ovpn.tmp"
	mv "$CONFIG_DIR/client.ovpn.tmp" "$CONFIG_DIR/client.ovpn"

	# Add \n at the end of the file only if it doesn't already end in a newline
	sed -i -e '$a\' "$CONFIG_DIR/client.ovpn"

	# Write paths config to file
	echo "status $TMP_DIR/openvpn-status.log" >> "$CONFIG_DIR/client.ovpn"
	echo "auth-user-pass $CONFIG_DIR/login.conf" >> "$CONFIG_DIR/client.ovpn"
	echo "route-up $DIR/scripts/vpn_up.sh" >> "$CONFIG_DIR/client.ovpn"
	echo "" >> "$CONFIG_DIR/client.ovpn"
	echo "### CUSTOM OPTIONS ###" >> "$CONFIG_DIR/client.ovpn"
}

# Call main function
main "$1"

exit 0