#!/bin/bash

# Add static config
SRV_LINE_FORMAT='^[a-zA-Z0-9]+\ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\ [0-9]+\ [a-z]{3}$'
CONFIG_DIR="/etc/secure-vpn"
TMP_DIR="/tmp/secure-vpn"

DIRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# If config file exist, include it
if [ -f "$CONFIG_DIR/config" ]; then
	# Load config file
	source "$CONFIG_DIR/config"
	CONFIG_SET=1
else
	CONFIG_SET=0
fi