#!/bin/bash

# Add static config
SRV_LINE_FORMAT='^[a-zA-Z0-9]+\ [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\ [0-9]+\ [a-z]{3}$'
CONFIG_DIR="/etc/secure-vpn"
TMP_DIR="/tmp/secure-vpn"

DIRC="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# If config file doesn't exist, call install script
if ! [ -f "$CONFIG_DIR/config" ]; then
	"$DIRC/../install" config
fi

# Load config file
source "$CONFIG_DIR/config"