#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Load config
source "$DIR/../config/loadConfig"

# Check if config has been set or not
if [ "$CONFIG_SET" -eq 0 ]; then
	echo "Please first install the script : ./install"
	echo "Then update config in $CONFIG_DIR."
	exit 1
fi

# ------------------------------------------------
# Get status of VPN connection
# ------------------------------------------------
function getStatus {
	ifconfig | grep "$1" && return 1
	return 0
}

# ------------------------------------------------
# Write all servers config to OpenVPN config file
# ------------------------------------------------
function writeAllServersConf {
	emptyServersConfig

	# Write protocol
	echo "proto $VPN_PROTO" >> "$CONFIG_DIR/client.ovpn"

	# Declare associative array
	declare -A loadedCerts

	# Write all servers
	while read server; do
		read srvName srvIp srvPort srvProto <<< $server

		# If server line is not correctly formated, exit
		if ! [[ "$server" =~ $SRV_LINE_FORMAT ]]; then
			exit 1
		fi

		# If server protocol is not the one in config, exit
		if [[ "$srvProto" != $VPN_PROTO ]]; then
			exit 1
		fi

		echo "remote $srvIp $srvPort" >> "$CONFIG_DIR/client.ovpn"

		# Only include cert if not already done
		if [[ ${loadedCerts[$srvName]} != 1 ]]; then
			loadedCerts[$srvName]=1
			echo "ca $CONFIG_DIR/certs/$srvName.crt" >> "$CONFIG_DIR/client.ovpn"
		fi
	done < "$CONFIG_DIR/servers.conf"
}

# ------------------------------------------------
# Write only one server config to OpenVPN config file
# ------------------------------------------------
function writeOneServerConf {
	emptyServersConfig

	# Get number of servers in config
	nbServers=$(wc -l < "$CONFIG_DIR/servers.conf")

	currServerLine=$1

	# Current server doesn't exist (number gt nbServers), exit
	if [ $currServerLine -gt $nbServers ]; then
		exit 1
	fi

	# Get server line from config
	server=$(sed -n "$[currServerLine]p" < "$CONFIG_DIR/servers.conf")

	# If server line is not correctly formated, exit
	if ! [[ "$server" =~ $SRV_LINE_FORMAT ]]; then
		exit 1
	fi

	# All is ok, parse infos
	read srvName srvIp srvPort srvProto <<< $server

	# Write server config to file
	echo "proto $srvProto" >> "$CONFIG_DIR/client.ovpn"
	echo "remote $srvIp $srvPort" >> "$CONFIG_DIR/client.ovpn"
	echo "ca $CONFIG_DIR/certs/$srvName.crt" >> "$CONFIG_DIR/client.ovpn"
}

# ------------------------------------------------
# Empty the server config in OpenVPN config file
# ------------------------------------------------
function emptyServersConfig {
	# Get line where the fun starts
	startLine=$(awk '$0 ~ str{print NR FS b}{b=$0}' str="### CUSTOM OPTIONS ##" "$CONFIG_DIR/client.ovpn")

	# Keep only first part of the file (remove "custom" options at the end)
	head -n $startLine "$CONFIG_DIR/client.ovpn" > "$CONFIG_DIR/client.ovpn.tmp"
	mv "$CONFIG_DIR/client.ovpn.tmp" "$CONFIG_DIR/client.ovpn"

	# Add \n at the end of the file only if it doesn't already end in a newline
	sed -i -e '$a\' "$CONFIG_DIR/client.ovpn"
}

# ------------------------------------------------
# If server line provided, load only this one.
# Else, load all servers.
# ------------------------------------------------
if [[ "$1" =~ ^[0-9]+$ ]]; then
	writeOneServerConf "$1"
else
	writeAllServersConf
fi

# ------------------------------------------------
# Infinite loop for daemon - check if VPN is up
# and restart it if needed. If can't connect to
# VPN server after 3 retry, load new server config.
# ------------------------------------------------
while :
do
	getStatus tun0
	if [[ $? == 0 ]]; then
		date
		echo "OpenVPN not connected !"

		echo "Connection to server..."

		openvpn --config "$CONFIG_DIR/client.ovpn"

		# Wait 1 minute before next check
		sleep 60
	else
		# Already connected, next check in 5 minutes
		sleep 300
	fi
done